#!/usr/bin/env bash
# install-hooks.sh — Install the corpus contract guard as a git pre-push hook.
#
# Usage (from repo root):
#   bash tools/install-hooks.sh
#
# The installed hook runs:
#   python tools/corpus_cli.py check
# before every push. Push is blocked if corpus and discovery are out of sync.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "")"
if [ -z "$REPO_ROOT" ]; then
  echo "ERROR: not inside a git repository."
  exit 1
fi

HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-push"
CLI_REL="tools/corpus_cli.py"

cat > "$HOOK_FILE" <<'HOOK'
#!/usr/bin/env bash
# pre-push hook: corpus contract guard (generated by tools/install-hooks.sh)
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
CLI="$REPO_ROOT/tools/corpus_cli.py"

if [ ! -f "$CLI" ]; then
  echo "  corpus_cli.py not found — skipping corpus check"
  exit 0
fi

echo "  [pre-push] running corpus check..."
if python "$CLI" check; then
  echo "  [pre-push] corpus check passed"
else
  echo ""
  echo "  PUSH BLOCKED: corpus and discovery are out of sync."
  echo "  Run: python tools/corpus_cli.py sync"
  echo "  Then commit the updated discovery/ files and push again."
  exit 1
fi
HOOK

chmod +x "$HOOK_FILE"
echo "Installed pre-push hook at $HOOK_FILE"
echo "The hook runs 'python $CLI_REL check' before every push."
